# Generated by Django 2.0 on 2017-12-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=32)),
                ('employment_type', models.CharField(max_length=32)),
                ('compensation', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('experience_required', models.CharField(max_length=32)),
                ('education', models.CharField(max_length=32)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=64)),
                ('industry', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('industry_experience', models.CharField(max_length=64)),
            ],
        ),
    ]
