# Generated by Django 2.0 on 2017-12-23 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 3, 3, 58, 726942, tzinfo=utc)),
        ),
    ]
