# Generated by Django 2.0 on 2018-01-13 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20180112_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 2, 11, 7, 182101, tzinfo=utc)),
        ),
    ]
