# Generated by Django 2.0 on 2018-01-13 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20180112_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 3, 17, 41, 612343, tzinfo=utc)),
        ),
    ]
