# Generated by Django 2.0 on 2017-12-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171219_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desired_industry',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
