# Generated by Django 2.0 on 2017-12-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employerprofile_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_employer',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
