# Generated by Django 2.0 on 2017-12-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171221_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
